Repository acemod/ACEX, pull requests merged in 2018-11, with the labels that each got.

#142 View Restriction - Replace deprecated function call
  addons/viewrestriction/functions/fnc_canChangeCamera.sqf
Labels: cleanup, enhancement

#141 Headless - Fix 3den default value
  addons/headless/CfgEden.hpp
Labels: bug fix

#138 View Restriction - Fix preserve view for vehicles with GUNNER view only
  addons/viewrestriction/functions/fnc_canChangeCamera.sqf
  addons/viewrestriction/functions/fnc_switchPreserveView.sqf
Labels: bug fix

#146 Replace placed modules by additional information in the issue template
  .github/ISSUE_TEMPLATE.md
Labels: ignore changelog, tools

#145 Headless - Fix end mission not respecting virtual curators
  addons/headless/functions/fnc_endMissionNoPlayers.sqf
  addons/headless/functions/fnc_handleConnectHC.sqf
  addons/headless/functions/fnc_handleDisconnect.sqf
  addons/headless/functions/fnc_handleSpawn.sqf
  addons/headless/functions/fnc_rebalance.sqf
  addons/headless/functions/fnc_transferGroups.sqf
Labels: bug fix

#144 Multi Player Sitting (rework #122)
  addons/sitting/CfgVehicles.hpp
  addons/sitting/XEH_clientInit.sqf
  addons/sitting/functions/fnc_addSitActions.sqf
  addons/sitting/functions/fnc_canSit.sqf
  addons/sitting/functions/fnc_canStand.sqf
  addons/sitting/functions/fnc_handleInterrupt.sqf
  addons/sitting/functions/fnc_sit.sqf
  addons/sitting/functions/fnc_stand.sqf
  addons/sitting/script_component.hpp
  tools/make.py
Labels: feature request

#147 Update Japanese translations
  addons/field_rations/stringtable.xml
Labels: translation

#152 Field Rations - Fix terrain objects acting as water sources
  addons/field_rations/functions/fnc_getRemainingWater.sqf
Labels: bug fix

#153 Field Rations - Fix no model for water pumps and add action offset
  addons/field_rations/CfgVehicles.hpp
Labels: bug fix

#154 Field Rations - Decrease refill action distance
  addons/field_rations/XEH_postInit.sqf
Labels: bug fix
