Repository acemod/ACEX, pull requests merged in 2018-02, with the labels that each got.

#109 Update Chinese Language
  addons/fortify/stringtable.xml
Labels: translation

#112 Fortify - Fix canInteractWith check
  addons/fortify/functions/fnc_deployObject.sqf
Labels: ignore changelog

#108 Remove redundant run at settings init in Sitting
  addons/sitting/functions/fnc_addSitActions.sqf
Labels: cleanup

#110 Fortify - Add events when creating / deleting objects
  addons/fortify/XEH_postInit.sqf
  addons/fortify/functions/fnc_deployConfirm.sqf
Labels: enhancement
