Repository acemod/ACEX, pull requests merged in 2018-08, with the labels that each got.

#131 Fortify - Improve deploy handlers check
  addons/fortify/functions/fnc_addDeployHandler.sqf
  addons/fortify/functions/fnc_deployObject.sqf
Labels: enhancement

#134 CBA Settings Compat - Hide setting modules
  addons/headless/CfgVehicles.hpp
  addons/sitting/CfgVehicles.hpp
  addons/viewrestriction/CfgVehicles.hpp
Labels: cleanup

#133 Fortify - Fix budget hint showing for all sides with tool setting
  addons/fortify/XEH_postInit.sqf
  addons/fortify/stringtable.xml
Labels: bug fix

#135 Update Japanese translation
  addons/fortify/stringtable.xml
Labels: translation
