Repository acemod/ACEX, pull requests merged in 2019-12, with the labels that each got.

#189 KillTracker - Rework for medRewrite
  addons/killtracker/XEH_postInit.sqf
Labels: enhancement

#11 Add Intel Items (Documents, Photos, Notepad)
  addons/intelitems/$PBOPREFIX$
  addons/intelitems/CfgEditorSubcategories.hpp
  addons/intelitems/CfgEventHandlers.hpp
  addons/intelitems/CfgMagazines.hpp
  addons/intelitems/CfgVehicles.hpp
  addons/intelitems/README.md
  addons/intelitems/XEH_PREP.hpp
  addons/intelitems/XEH_postInit.sqf
  addons/intelitems/XEH_preInit.sqf
  addons/intelitems/XEH_preStart.sqf
  addons/intelitems/config.cpp
  addons/intelitems/functions/fnc_addActions.sqf
  addons/intelitems/functions/fnc_attributeFocus.sqf
  addons/intelitems/functions/fnc_canPickup.sqf
  addons/intelitems/functions/fnc_createControl.sqf
  addons/intelitems/functions/fnc_deleteControl.sqf
  addons/intelitems/functions/fnc_handleLoadout.sqf
  addons/intelitems/functions/fnc_handleMagIndex.sqf
  addons/intelitems/functions/fnc_onMouseButtonDown.sqf
  addons/intelitems/functions/fnc_onMouseButtonUp.sqf
  addons/intelitems/functions/fnc_onMouseMoving.sqf
  addons/intelitems/functions/fnc_pickup.sqf
  addons/intelitems/functions/fnc_setObjectData.sqf
  addons/intelitems/functions/script_component.hpp
  addons/intelitems/gui.hpp
  addons/intelitems/script_component.hpp
  addons/intelitems/stringtable.xml
  addons/intelitems/ui/document_ca.paa
  addons/intelitems/ui/notepad_ca.paa
  addons/intelitems/ui/photo_ca.paa
Labels: feature request

#199 Update tchinese string
  addons/intelitems/stringtable.xml
Labels: translation

#200 IntelItems - Remove condition from attributes
  addons/intelitems/CfgVehicles.hpp
Labels: bug fix, ignore changelog

#202 update tch string on field_rations
  addons/field_rations/stringtable.xml
Labels: translation

#201 Update Japanese translation
  addons/intelitems/stringtable.xml
Labels: translation
