Repository acemod/ACEX, pull requests merged in 2019-02, with the labels that each got.

#164 Field Rations - Add water supply 3DEN attribute
  addons/field_rations/Cfg3DEN.hpp
  addons/field_rations/config.cpp
  addons/field_rations/stringtable.xml
Labels: enhancement

#167 Field Rations - Add setting to control effect on advanced fatigue
  addons/field_rations/XEH_postInit.sqf
  addons/field_rations/initSettings.sqf
  addons/field_rations/stringtable.xml
Labels: enhancement

#170 Field Rations - Add P3Ds From Config
  addons/field_rations/CfgVehicles.hpp
  addons/field_rations/XEH_preInit.sqf
  addons/field_rations/XEH_preStart.sqf
Labels: enhancement

#163 Add naked unit bug workaround
  addons/headless/XEH_postInit.sqf
  addons/headless/XEH_preInit.sqf
  addons/headless/functions/fnc_transferGroups.sqf
  addons/headless/initSettings.sqf
  addons/headless/stringtable.xml
Labels: BIS' fault, bug fix, needs testing

#175 then
  addons/headless/functions/fnc_transferGroups.sqf
Labels: ignore changelog

#176 Headless - varname fix and add logging
  addons/headless/XEH_postInit.sqf
  addons/headless/initSettings.sqf
Labels: ignore changelog

#177 Update Japanese translation
  addons/field_rations/stringtable.xml
  addons/headless/stringtable.xml
Labels: translation
