Repository acemod/ACEX, pull requests merged in 2020-06, with the labels that each got.

#234 Sitting - Fix interaction condition
  addons/sitting/XEH_clientInit.sqf
Labels: bug fix

#229 Field rations - Add inventory context menu action
  addons/field_rations/XEH_postInit.sqf
  addons/field_rations/functions/fnc_addStatusModifier.sqf
  addons/field_rations/functions/fnc_addWaterSourceInteractions.sqf
  addons/field_rations/functions/fnc_canRefillItem.sqf
  addons/field_rations/functions/fnc_checkWater.sqf
  addons/field_rations/functions/fnc_consumeItem.sqf
  addons/field_rations/functions/fnc_drinkFromSource.sqf
  addons/field_rations/functions/fnc_getActionOffset.sqf
  addons/field_rations/functions/fnc_getConsumableChildren.sqf
  addons/field_rations/functions/fnc_getRefillChildren.sqf
  addons/field_rations/functions/fnc_getRemainingWater.sqf
  addons/field_rations/functions/fnc_handleHUD.sqf
  addons/field_rations/functions/fnc_handleRespawn.sqf
  addons/field_rations/functions/fnc_refillItem.sqf
  addons/field_rations/functions/fnc_setRemainingWater.sqf
  addons/field_rations/functions/fnc_update.sqf
  addons/field_rations/stringtable.xml
  addons/fortify/XEH_postInit.sqf
  addons/fortify/functions/fnc_addActions.sqf
  addons/fortify/functions/fnc_axisLengths.sqf
  addons/fortify/functions/fnc_canFortify.sqf
  addons/fortify/functions/fnc_deployObject.sqf
  addons/fortify/functions/fnc_getBudget.sqf
  addons/fortify/functions/fnc_getCost.sqf
  addons/fortify/functions/fnc_modifyAction.sqf
  addons/fortify/functions/fnc_parseSide.sqf
  addons/fortify/functions/fnc_registerObjects.sqf
  addons/fortify/functions/fnc_updateBudget.sqf
  addons/fortify/initSettings.sqf
  addons/headless/initSettings.sqf
  addons/intelitems/functions/fnc_setObjectData.sqf
  addons/sitting/functions/fnc_addSitActions.sqf
  addons/sitting/functions/fnc_sit.sqf
  addons/viewrestriction/initSettings.sqf
  addons/volume/XEH_postInitClient.sqf
  addons/volume/functions/fnc_lowerVolume.sqf
  addons/volume/functions/fnc_remind.sqf
  addons/volume/functions/fnc_restoreVolume.sqf
Labels: enhancement

#235 Translations - Russian
  AUTHORS.txt
  addons/field_rations/stringtable.xml
  addons/fortify/stringtable.xml
  addons/headless/stringtable.xml
  addons/intelitems/stringtable.xml
Labels: translation

#231 Add localized entries for acex_killtracker
  addons/killtracker/XEH_postInit.sqf
  addons/killtracker/stringtable.xml
Labels: cleanup, translation

#238 Fortify - Make module dynamically check config for presets
  addons/fortify/ACEX_Fortify_Presets.hpp
  addons/fortify/Cfg3DEN.hpp
  addons/fortify/CfgVehicles.hpp
  addons/fortify/config.cpp
  addons/fortify/functions/fnc_setupModule.sqf
  addons/fortify/stringtable.xml
Labels: enhancement

#208 Translations - German
  addons/field_rations/stringtable.xml
  addons/fortify/stringtable.xml
  addons/headless/stringtable.xml
  addons/intelitems/stringtable.xml
  addons/viewrestriction/stringtable.xml
  addons/volume/stringtable.xml
Labels: translation

#239 Add missing Polish translations
  addons/field_rations/stringtable.xml
  addons/fortify/stringtable.xml
  addons/headless/stringtable.xml
  addons/intelitems/stringtable.xml
  addons/killtracker/stringtable.xml
  addons/viewrestriction/stringtable.xml
  addons/volume/stringtable.xml
Labels: translation

#240 Improve stringtable validator
  tools/stringtable_validator.py
Labels: tools

#242 Update release-drafter.yml
  .github/release-drafter.yml
Labels: ignore changelog
