Repository acemod/ACEX, pull requests merged in 2020-02, with the labels that each got.

#211 Kill Tracker - Support custom AI names
  addons/killtracker/XEH_postInit.sqf
Labels: enhancement

#206 Field Rations - Disable for virtual units, Hide HUD in feature cameras
  addons/field_rations/XEH_postInit.sqf
  addons/field_rations/functions/fnc_handleHUD.sqf
  addons/field_rations/functions/fnc_update.sqf
Labels: enhancement

#207 Fortify - Display cost of item at start of interaction text
  addons/fortify/functions/fnc_addActions.sqf
Labels: enhancement

#204 Field Rations - Add ability to drink from source
  addons/field_rations/CfgMoves.hpp
  addons/field_rations/CfgVehicles.hpp
  addons/field_rations/XEH_PREP.hpp
  addons/field_rations/XEH_postInit.sqf
  addons/field_rations/anim/drink_source.rtm
  addons/field_rations/anim/drink_source_high.rtm
  addons/field_rations/anim/drink_source_low.rtm
  addons/field_rations/anim/drink_source_squat.rtm
  addons/field_rations/anim/drink_source_squat_high.rtm
  addons/field_rations/anim/drink_source_squat_low.rtm
  addons/field_rations/functions/fnc_addWaterSourceInteractions.sqf
  addons/field_rations/functions/fnc_canDrinkFromSource.sqf
  addons/field_rations/functions/fnc_canRefillItem.sqf
  addons/field_rations/functions/fnc_consumeItem.sqf
  addons/field_rations/functions/fnc_drinkFromSource.sqf
  addons/field_rations/functions/fnc_getDrinkAnimation.sqf
  addons/field_rations/initSettings.sqf
  addons/field_rations/script_component.hpp
  addons/field_rations/stringtable.xml
Labels: feature request

#205 Field Rations - Fix changing HUD type while HUD is shown
  addons/field_rations/initSettings.sqf
Labels: bug fix

#203 Intel Items - Add function to add item to unit with data
  addons/intelitems/XEH_PREP.hpp
  addons/intelitems/functions/fnc_addIntel.sqf
  addons/intelitems/functions/fnc_handleMagIndex.sqf
  addons/intelitems/stringtable.xml
Labels: feature request

#212 Fortify - Fix interaction overlapping remove object interaction
  addons/fortify/XEH_postInit.sqf
Labels: bug fix
