Repository acemod/ACEX, pull requests merged in 2020-03, with the labels that each got.

#214 Tools - Add Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ignore changelog, tools

#216 Tools - Update GitHub config (Stale and Issue Templates)
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/stale.yml
Labels: ignore changelog, tools

#215 Tools - Move to GitHub Actions
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
  .github_changelog_generator
  .gitignore
  .travis.yml
  addons/fortify/script_component.hpp
  addons/main/CfgEventHandlers.hpp
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postInit.sqf
  addons/main/XEH_preInit.sqf
  addons/main/XEH_preStart.sqf
  addons/main/config.cpp
  circle.yml
  hemtt.toml
  include/a3/ui_f/$PBOPREFIX$
  include/a3/ui_f/hpp/defineCommonColors.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
  include/a3/ui_f/hpp/defineResinclDesign.inc
  include/x/cba/addons/main/$PBOPREFIX$
  include/x/cba/addons/main/script_macros_common.hpp
  include/x/cba/addons/xeh/$PBOPREFIX$
  include/x/cba/addons/xeh/script_xeh.hpp
  include/z/ace/addons/main/$PBOPREFIX$
  include/z/ace/addons/main/script_debug.hpp
  include/z/ace/addons/main/script_macros.hpp
  tools/check_strings.py
  tools/stringtable_validator.py
Labels: ignore changelog, tools

#217 Fortify - Add green presets to setup module
  addons/fortify/ACEX_Fortify_Presets.hpp
  addons/fortify/CfgVehicles.hpp
  addons/fortify/functions/fnc_setupModule.sqf
  addons/fortify/stringtable.xml
Labels: enhancement

#218 Tools - Use `GITHUB_TOKEN` in documentation workflow
  .github/workflows/documentation.yml
Labels: bug fix, ignore changelog, tools

#219 General - Increase required ACE3 version
  addons/main/script_mod.hpp
Labels: bug fix, ignore changelog

#220 Field Rations - Add missing interaction offsets
  addons/field_rations/CfgVehicles.hpp
  addons/field_rations/XEH_preStart.sqf
Labels: enhancement

#221 Field Rations - Fix interaction position for moving objects
  addons/field_rations/functions/fnc_addWaterSourceInteractions.sqf
Labels: bug fix

#222 Tools - Removed deprecated Mikero tools arguments from make.py
  tools/make.py
Labels: ignore changelog, tools

#223 Tools - Enable CI BOM Check
  .github/workflows/arma.yml
Labels: ignore changelog, tools

#225 Intel Items - Fix addIntel addMagazine locality
  addons/intelitems/functions/fnc_addIntel.sqf
Labels: bug fix

#228 Make Thirst Quenched Coefficient Effect Water Sources
  addons/field_rations/functions/fnc_drinkFromSource.sqf
Labels: bug fix

#227 Kill Tracker - Fix reported unit type
  addons/killtracker/README.md
  addons/killtracker/XEH_postInit.sqf
Labels: bug fix
